name: calendar-app
region: fra
static_sites:
  - name: calendar
    github:
      repo: truemanD/calendar-app
      branch: main
      deploy_on_push: true
    build_command: echo "No build needed"
    output_dir: /
    routes:
      - path: /
    catchall_document: index.html
